POST http://localhost:5050/api/signup
Content-Type: application/json

{
  "name": "John Doe 2",
  "email": "john.doe2@mail.com",
  "password": "123456",
  "passwordConfirmation": "123456"
}

###

POST http://localhost:5050/api/login
Content-Type: application/json

{
  "email": "john.doe2@mail.com",
  "password": "123456"
}

###


POST http://localhost:5050/api/surveys
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDM4ZGFjMjAwNWE2MTAwMzU4ZDkyNyIsImlhdCI6MTY0ODU5NDM0OH0.j2ORA679qxSoiHf7DQoiLv96v6MzaPsYIYzCqELdiE0

{
  "question": "Question 1",
  "answers": [
    {
      "answer": "Answer 1",
      "image": "image-name.jpg"
    }
  ]
}
