### signup

POST http://localhost:5050/api/signup
Content-Type: application/json

{
  "name": "John Doe 2",
  "email": "john.doe2@mail.com",
  "password": "123456",
  "passwordConfirmation": "123456"
}

### login

POST http://localhost:5050/api/login
Content-Type: application/json

{
  "email": "john.doe2@mail.com",
  "password": "123456"
}

### add surveys

POST http://localhost:5050/api/surveys
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDM4ZGFjMjAwNWE2MTAwMzU4ZDkyNyIsImlhdCI6MTY0ODU5NDM0OH0.j2ORA679qxSoiHf7DQoiLv96v6MzaPsYIYzCqELdiE0

{
  "question": "Question 1",
  "answers": [
    {
      "answer": "Answer 1",
      "image": "image-name.jpg"
    }
  ]
}

### load surveys

GET http://localhost:5050/api/surveys
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDM4ZGFjMjAwNWE2MTAwMzU4ZDkyNyIsImlhdCI6MTY0OTg5Njk2OH0.k37BQWGglT8KZWtp8fzWdFePwBPnHlRGSeILaSx9fs0


### save survey result

PUT http://localhost:5050/api/surveys/623787417bed337c7e649527/results
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDM4ZGFjMjAwNWE2MTAwMzU4ZDkyNyIsImlhdCI6MTY0OTg5Njk2OH0.k37BQWGglT8KZWtp8fzWdFePwBPnHlRGSeILaSx9fs0

{
  "answer": "Answer 1"
}

### Docs

GET http://localhost:5050/api-docs/
