version: '3'

services:
  db:
    image: mongo:4.0.24
    environment:
      - MONGO_INITDB_DATABASE=clean-node-api
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=12345
      - MONGO_APPLICATION_DATABASE=clean-node-api
      - MONGO_APPLICATION_USERNAME=clean
      - MONGO_APPLICATION_PASSWORD=12345
    ports:
      - 27017:27017
    # volumes:
    #   - ./.docker/mongo/db:/data/db
    #   - ./.docker/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
