version: '3'

services:
  mongo:
    container_name: mongo-container
    image: mongo:4.0.24
    # restart: always
    environment:
      - MONGO_INITDB_DATABASE=clean-node-api
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=12345
      - MONGO_APPLICATION_DATABASE=clean-node-api
      - MONGO_APPLICATION_USERNAME=clean
      - MONGO_APPLICATION_PASSWORD=12345
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
      # - ./.docker/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
  api:
    container_name: api-container
    image: node:14
    working_dir: /usr/src/clean-node-api
    # restart: always
    command: bash -c "npm install --only-prod && npm run debug"
    volumes:
      - ./dist:/usr/src/clean-node-api/dist
      - ./package.json:/usr/src/clean-node-api/package.json
    ports:
      - 5050:5050
      - 9222:9222
    links:
      - mongo
