version: '3'

services:
  mongo:
    container_name: mongo-container
    image: mongo:4.0.24
    # restart: always
    environment:
      - MONGO_INITDB_DATABASE=clean-node-api
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=12345
      - MONGO_APPLICATION_DATABASE=clean-node-api
      - MONGO_APPLICATION_USERNAME=clean
      - MONGO_APPLICATION_PASSWORD=12345
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
      # - ./.docker/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
  api:
    container_name: api-container
    image: node:14
    working_dir: /usr/src/clean-node-api
    # restart: always
    # command: bash -c "npm install --only-prod && npm run debug"
    command: bash -c "npm install && npm run build && npm run debug"
    environment:
      - MONGO_URL=mongodb://root:12345@mongo:27017/clean-node-api?authSource=admin
    volumes:
      - .:/usr/src/clean-node-api
      - /node_modules
      # /usr/src/clean-node-api/node_modules
    ports:
      - 5050:5050
      - 9222:9222
    links:
      - mongo
